### ISSUE TITLE
Cannot enable the mod.

### ISSUE THREAD

**Issue by febzen** [Deji69/Stealthometer#6]
![image_2024-05-05_200529900](https://github.com/Deji69/Stealthometer/assets/88053316/c04514f5-e3ba-4b9e-87ff-ca1b01823a95)

Couldn't find what to do.

**Comment by febzen** [comment]
![image_2024-05-05_200729683](https://github.com/Deji69/Stealthometer/assets/88053316/3d604c0a-0697-4aa4-9285-4a5a101484ce)

"Game version on Steam"

**Comment by Deji69** [comment]
The currently released version of Stealthometer (v0.2.1) will work with [ZHMModSDK version v2.0.0-rc3](https://github.com/OrfeasZ/ZHMModSDK/tree/v2.0.0-rc.3) (release candidate). The latest official release version of ZHMModSDK (v2.0.0) is not compatible.

I will try to release an update for Stealthometer soon in order to support SDK v2.0.0.

**Comment by Deji69** [comment]
v0.3 release adds ZHMModSDK v2.0.0 support: https://github.com/Deji69/Stealthometer/releases/tag/v0.3
